# Generated by Django 5.2.11 on 2026-02-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('service', models.CharField(blank=True, choices=[('seguridad-electronica', 'Seguridad Electronica'), ('seguridad-fisica', 'Seguridad Fisica'), ('limpieza', 'Limpieza y Mantenimiento'), ('saneamiento', 'Saneamiento Ambiental'), ('consultoria', 'Consultoria'), ('otro', 'Otro')], max_length=100, verbose_name='Servicio')),
                ('other_service_detail', models.CharField(blank=True, max_length=200, verbose_name='Detalle otro servicio')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('privacy_accepted', models.BooleanField(default=False, verbose_name='Acepto politica de privacidad')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leido')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Puesto laboral',
                'verbose_name_plural': 'Puestos laborales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('cv_file', models.FileField(upload_to='cvs/', verbose_name='CV')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Revisado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms_app.jobposition', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Postulacion laboral',
                'verbose_name_plural': 'Postulaciones laborales',
                'ordering': ['-created_at'],
            },
        ),
    ]
