# Generated by Django 5.2.11 on 2026-02-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_cv', models.BooleanField(default=False, verbose_name='Tiene CV')),
                ('title', models.CharField(blank=True, choices=[('Sr', 'Sr.'), ('Sra', 'Sra.'), ('Srta', 'Srta.')], max_length=10, verbose_name='Titulo')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Direccion')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Codigo postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Departamento/Estado')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pais')),
                ('preferred_language', models.CharField(choices=[('es', 'Espanol'), ('en', 'Ingles'), ('pt', 'Portugues')], default='es', max_length=5, verbose_name='Idioma preferido')),
                ('cv_file', models.FileField(blank=True, upload_to='aplicar/cv/', verbose_name='Curriculum Vitae')),
                ('cover_letter', models.FileField(blank=True, upload_to='aplicar/cover/', verbose_name='Carta de presentacion')),
                ('certificates', models.FileField(blank=True, upload_to='aplicar/certificates/', verbose_name='Certificados')),
                ('other_files', models.FileField(blank=True, upload_to='aplicar/other/', verbose_name='Otros archivos')),
                ('has_driver_license', models.BooleanField(default=False, verbose_name='Tiene licencia de conducir')),
                ('driver_license_category', models.CharField(blank=True, max_length=20, verbose_name='Categoria de licencia')),
                ('has_criminal_record', models.BooleanField(default=False, verbose_name='Tiene antecedentes penales')),
                ('criminal_record_detail', models.CharField(blank=True, max_length=300, verbose_name='Detalle antecedentes')),
                ('has_health_issues', models.BooleanField(default=False, verbose_name='Tiene problemas de salud')),
                ('health_issues_detail', models.CharField(blank=True, max_length=300, verbose_name='Detalle problemas de salud')),
                ('available_immediately', models.BooleanField(default=False, verbose_name='Disponibilidad inmediata')),
                ('available_travel', models.BooleanField(default=False, verbose_name='Disponible para viajar')),
                ('available_relocate', models.BooleanField(default=False, verbose_name='Disponible para reubicacion')),
                ('has_own_vehicle', models.BooleanField(default=False, verbose_name='Tiene vehiculo propio')),
                ('english_level', models.CharField(choices=[('none', 'Ninguno'), ('basic', 'Basico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('native', 'Nativo')], default='none', max_length=20, verbose_name='Nivel de ingles')),
                ('excel_level', models.CharField(choices=[('none', 'Ninguno'), ('basic', 'Basico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='none', max_length=20, verbose_name='Nivel de Excel')),
                ('logistics_experience', models.CharField(choices=[('none', 'Ninguna'), ('less_1', 'Menos de 1 ano'), ('1_3', '1 a 3 anos'), ('3_5', '3 a 5 anos'), ('more_5', 'Mas de 5 anos')], default='none', max_length=20, verbose_name='Experiencia en logistica')),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salario esperado (S/.)')),
                ('current_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salario actual (S/.)')),
                ('how_found', models.CharField(blank=True, choices=[('web', 'Pagina web'), ('social', 'Redes sociales'), ('referral', 'Referido'), ('job_portal', 'Portal de empleo'), ('other', 'Otro')], max_length=20, verbose_name='Como se entero')),
                ('how_found_detail', models.CharField(blank=True, max_length=200, verbose_name='Detalle como se entero')),
                ('has_worked_here_before', models.BooleanField(default=False, verbose_name='Ha trabajado aqui antes')),
                ('worked_here_detail', models.CharField(blank=True, max_length=300, verbose_name='Detalle trabajo previo')),
                ('has_relatives_here', models.BooleanField(default=False, verbose_name='Tiene familiares en la empresa')),
                ('relatives_detail', models.CharField(blank=True, max_length=300, verbose_name='Detalle familiares')),
                ('additional_info', models.TextField(blank=True, verbose_name='Informacion adicional')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Revisado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_applications', to='forms_app.jobposition', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Postulacion completa',
                'verbose_name_plural': 'Postulaciones completas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('degree', models.CharField(blank=True, choices=[('secondary', 'Secundaria'), ('technical', 'Tecnico'), ('bachelor', 'Bachiller'), ('licentiate', 'Licenciatura'), ('master', 'Maestria'), ('doctorate', 'Doctorado'), ('other', 'Otro')], max_length=20, verbose_name='Grado')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de graduacion')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Universidad/Instituto')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='Nota/Promedio')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_formations', to='forms_app.fulljobapplication', verbose_name='Postulacion')),
            ],
            options={
                'verbose_name': 'Formacion academica',
                'verbose_name_plural': 'Formaciones academicas',
                'ordering': ['-graduation_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('position', models.CharField(max_length=200, verbose_name='Puesto')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='forms_app.fulljobapplication', verbose_name='Postulacion')),
            ],
            options={
                'verbose_name': 'Experiencia laboral',
                'verbose_name_plural': 'Experiencias laborales',
                'ordering': ['-start_date'],
            },
        ),
    ]
