# Generated by Django 5.2.11 on 2026-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_fulljobapplication_academicformation_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripcion')),
            ],
            options={
                'verbose_name': 'Suscripcion al boletin',
                'verbose_name_plural': 'Suscripciones al boletin',
                'ordering': ['-created_at'],
            },
        ),
    ]
