# Generated by Django 5.2.11 on 2026-02-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Numero de reclamo')),
                ('consumer_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('consumer_document_type', models.CharField(choices=[('dni', 'DNI'), ('ce', 'Carnet de Extranjeria'), ('pasaporte', 'Pasaporte'), ('ruc', 'RUC')], default='dni', max_length=20, verbose_name='Tipo de documento')),
                ('consumer_document_number', models.CharField(max_length=20, verbose_name='Numero de documento')),
                ('consumer_address', models.CharField(max_length=300, verbose_name='Domicilio')),
                ('consumer_phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('consumer_email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('service_type', models.CharField(choices=[('transporte_carga', 'Transporte de Carga'), ('transporte_personal', 'Transporte de Personal'), ('logistica', 'Servicios Logisticos'), ('almacenaje', 'Almacenaje'), ('distribucion', 'Distribucion'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de servicio')),
                ('service_description', models.TextField(verbose_name='Descripcion del servicio contratado')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='Fecha del servicio')),
                ('service_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de la transaccion (S/.)')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Numero de factura/boleta')),
                ('complaint_type', models.CharField(choices=[('reclamo', 'RECLAMO - Disconformidad relacionada con productos o servicios'), ('queja', 'QUEJA - Disconformidad no relacionada con productos/servicios')], max_length=20, verbose_name='Tipo')),
                ('complaint_detail', models.TextField(verbose_name='Detalle del reclamo/queja')),
                ('consumer_request', models.TextField(verbose_name='Pedido del consumidor')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('respondido', 'Respondido'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('assigned_to', models.CharField(blank=True, max_length=200, verbose_name='Asignado a')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('response', models.TextField(blank=True, verbose_name='Respuesta al consumidor')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de presentacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Libro de Reclamaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='forms_app_c_created_12f347_idx'), models.Index(fields=['status'], name='forms_app_c_status_f58d1b_idx'), models.Index(fields=['claim_number'], name='forms_app_c_claim_n_9d5b2f_idx')],
            },
        ),
    ]
