# Generated by Django 5.2.11 on 2026-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_claimbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='service',
            field=models.CharField(blank=True, choices=[('transporte', 'Transporte'), ('almacen', 'Almacén'), ('alquiler', 'Alquiler'), ('otros', 'Otros')], max_length=100, verbose_name='Servicio'),
        ),
    ]
