# Generated by Django 5.2.11 on 2026-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='Sitio web')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BRIANE', max_length=200, verbose_name='Nombre')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Eslogan')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('mission', models.TextField(blank=True, verbose_name='Mision')),
                ('vision', models.TextField(blank=True, verbose_name='Vision')),
                ('values', models.JSONField(blank=True, default=list, verbose_name='Valores')),
                ('address', models.TextField(blank=True, verbose_name='Direccion')),
                ('phones', models.JSONField(blank=True, default=list, verbose_name='Telefonos')),
                ('emails', models.JSONField(blank=True, default=list, verbose_name='Correos electronicos')),
                ('hours', models.CharField(blank=True, max_length=200, verbose_name='Horario de atencion')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Redes sociales')),
                ('google_maps_embed_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Google Maps')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='Numero de WhatsApp')),
            ],
            options={
                'verbose_name': 'Informacion de la empresa',
                'verbose_name_plural': 'Informacion de la empresa',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Imagen')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('suffix', models.CharField(blank=True, max_length=20, verbose_name='Sufijo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estadistica',
                'verbose_name_plural': 'Estadisticas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('image', models.ImageField(blank=True, upload_to='team/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
                'ordering': ['order'],
            },
        ),
    ]
