# Generated by Django 5.2.11 on 2026-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('equipo', 'Equipo'), ('eventos', 'Eventos'), ('academia', 'Academia'), ('proyectos', 'Proyectos'), ('oficina', 'Oficina')], max_length=50, verbose_name='Categoria')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagen')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('person_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre de persona')),
                ('person_comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen de galeria',
                'verbose_name_plural': 'Imagenes de galeria',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(db_index=True, max_length=100, verbose_name='Pagina')),
                ('section_key', models.CharField(max_length=100, verbose_name='Seccion')),
                ('image', models.ImageField(upload_to='pages/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Leyenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen de pagina',
                'verbose_name_plural': 'Imagenes de pagina',
                'ordering': ['page_slug', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(db_index=True, max_length=100, verbose_name='Pagina')),
                ('section_key', models.CharField(max_length=100, verbose_name='Seccion')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titulo')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Contenido de pagina',
                'verbose_name_plural': 'Contenidos de pagina',
                'ordering': ['page_slug', 'order'],
                'unique_together': {('page_slug', 'section_key')},
            },
        ),
    ]
