# Generated by Django 5.2.11 on 2026-02-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('equipo', 'Equipo'), ('eventos', 'Eventos'), ('comunidad', 'Comunidad'), ('academia', 'Academia'), ('proyectos', 'Proyectos'), ('oficina', 'Oficina')], max_length=50, verbose_name='Categoria'),
        ),
    ]
