# Generated by Django 5.2.11 on 2026-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Descripcion corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Caracteristicas')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Imagen')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order'],
            },
        ),
    ]
